.PHONY: clean All

All:
	@echo "----------Building project:[ cpp_strings - Debug ]----------"
	@cd "cpp_strings" && "$(MAKE)" -f  "cpp_strings.mk"
clean:
	@echo "----------Cleaning project:[ cpp_strings - Debug ]----------"
	@cd "cpp_strings" && "$(MAKE)" -f  "cpp_strings.mk" clean
