.PHONY: clean All

All:
	@echo "----------Building project:[ looping_for_while_etc - Debug ]----------"
	@cd "looping_for_while_etc" && "$(MAKE)" -f  "looping_for_while_etc.mk"
clean:
	@echo "----------Cleaning project:[ looping_for_while_etc - Debug ]----------"
	@cd "looping_for_while_etc" && "$(MAKE)" -f  "looping_for_while_etc.mk" clean
