.PHONY: clean All

All:
	@echo "----------Building project:[ VectorsArraysChallenge - Debug ]----------"
	@cd "VectorsArraysChallenge" && "$(MAKE)" -f  "VectorsArraysChallenge.mk"
clean:
	@echo "----------Cleaning project:[ VectorsArraysChallenge - Debug ]----------"
	@cd "VectorsArraysChallenge" && "$(MAKE)" -f  "VectorsArraysChallenge.mk" clean
