.PHONY: clean All

All:
	@echo "----------Building project:[ section_challenge_2 - Debug ]----------"
	@cd "section_challenge_2" && "$(MAKE)" -f  "section_challenge_2.mk"
clean:
	@echo "----------Cleaning project:[ section_challenge_2 - Debug ]----------"
	@cd "section_challenge_2" && "$(MAKE)" -f  "section_challenge_2.mk" clean
