.PHONY: clean All

All:
	@echo "----------Building project:[ section12_challenge - Debug ]----------"
	@cd "section12_challenge" && "$(MAKE)" -f  "section12_challenge.mk"
clean:
	@echo "----------Cleaning project:[ section12_challenge - Debug ]----------"
	@cd "section12_challenge" && "$(MAKE)" -f  "section12_challenge.mk" clean
