.PHONY: clean All

All:
	@echo "----------Building project:[ assignment_1 - Debug ]----------"
	@cd "assignment_1" && "$(MAKE)" -f  "assignment_1.mk"
clean:
	@echo "----------Cleaning project:[ assignment_1 - Debug ]----------"
	@cd "assignment_1" && "$(MAKE)" -f  "assignment_1.mk" clean
