.PHONY: clean All

All:
	@echo "----------Building project:[ code - Debug ]----------"
	@cd "code" && "$(MAKE)" -f  "code.mk"
clean:
	@echo "----------Cleaning project:[ code - Debug ]----------"
	@cd "code" && "$(MAKE)" -f  "code.mk" clean
