.PHONY: clean All

All:
	@echo "----------Building project:[ section8Challenge - Debug ]----------"
	@cd "section8Challenge" && "$(MAKE)" -f  "section8Challenge.mk"
clean:
	@echo "----------Cleaning project:[ section8Challenge - Debug ]----------"
	@cd "section8Challenge" && "$(MAKE)" -f  "section8Challenge.mk" clean
