.PHONY: clean All

All:
	@echo "----------Building project:[ lectureScripts - Debug ]----------"
	@cd "lectureScripts" && "$(MAKE)" -f  "lectureScripts.mk"
clean:
	@echo "----------Cleaning project:[ lectureScripts - Debug ]----------"
	@cd "lectureScripts" && "$(MAKE)" -f  "lectureScripts.mk" clean
