.PHONY: clean All

All:
	@echo "----------Building project:[ section_challenge - Debug ]----------"
	@cd "section_challenge" && "$(MAKE)" -f  "section_challenge.mk"
clean:
	@echo "----------Cleaning project:[ section_challenge - Debug ]----------"
	@cd "section_challenge" && "$(MAKE)" -f  "section_challenge.mk" clean
