.PHONY: clean All

All:
	@echo "----------Building project:[ Fibonacci - Debug ]----------"
	@cd "Fibonacci" && "$(MAKE)" -f  "Fibonacci.mk"
clean:
	@echo "----------Cleaning project:[ Fibonacci - Debug ]----------"
	@cd "Fibonacci" && "$(MAKE)" -f  "Fibonacci.mk" clean
