.PHONY: clean All

All:
	@echo "----------Building project:[ lecture_exercises - Debug ]----------"
	@cd "lecture_exercises" && "$(MAKE)" -f  "lecture_exercises.mk"
clean:
	@echo "----------Cleaning project:[ lecture_exercises - Debug ]----------"
	@cd "lecture_exercises" && "$(MAKE)" -f  "lecture_exercises.mk" clean
