.PHONY: clean All

All:
	@echo "----------Building project:[ section13_challenge - Debug ]----------"
	@cd "section13_challenge" && "$(MAKE)" -f  "section13_challenge.mk"
clean:
	@echo "----------Cleaning project:[ section13_challenge - Debug ]----------"
	@cd "section13_challenge" && "$(MAKE)" -f  "section13_challenge.mk" clean
