.PHONY: clean All

All:
	@echo "----------Building project:[ function_overloading - Debug ]----------"
	@cd "function_overloading" && "$(MAKE)" -f  "function_overloading.mk"
clean:
	@echo "----------Cleaning project:[ function_overloading - Debug ]----------"
	@cd "function_overloading" && "$(MAKE)" -f  "function_overloading.mk" clean
